"use client";

import { useState } from "react";
import { ArrowDownRight, ArrowUpRight, CalendarDays, ChevronDown, CircleDollarSign, LayoutDashboard, Plus, ReceiptText, Search, Settings, Target, WalletCards } from "lucide-react";
import { accounts, budgets, payments as initialPayments, transactions as initialTransactions } from "@/lib/demo-data";
import type { Payment, Transaction } from "@/lib/types";
import { AuthGate } from "@/app/auth-gate";
import { AccountsView } from "@/components/accounts/accounts-view";
import { AssistantWidget } from "@/components/assistant/assistant-widget";
import { BudgetView } from "@/components/budgets/budget-view";
import { DashboardView } from "@/components/dashboard/dashboard-view";
import { PaymentsView } from "@/components/payments/payments-view";
import { EntryModal } from "@/components/transactions/entry-modal";
import { TransactionsView } from "@/components/transactions/transactions-view";

const money = new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 });
const shortDate = (value: string) => new Intl.DateTimeFormat("es-AR", { day: "2-digit", month: "short" }).format(new Date(`${value}T12:00:00`));
const monthName = new Intl.DateTimeFormat("es-AR", { month: "long", year: "numeric" });
type View = "Resumen" | "Movimientos" | "Presupuesto" | "Cuentas" | "Pagos";

function currentMonth() {
  return new Date().toISOString().slice(0, 7);
}

function monthStart(month: string) {
  return `${month}-01`;
}

function monthLabel(month: string) {
  const label = monthName.format(new Date(`${monthStart(month)}T12:00:00`));
  return label.charAt(0).toUpperCase() + label.slice(1);
}

export default function Home() {
  const [view,setView]=useState<View>("Resumen");const [selectedMonth,setSelectedMonth]=useState(currentMonth());const [transactions,setTransactions]=useState(initialTransactions);const [payments,setPayments]=useState(initialPayments);const [modal,setModal]=useState<"transaction"|"payment"|null>(null);
  const available=accounts.reduce((sum,a)=>sum+a.balance,0);const pending=payments.filter(p=>p.status==="pending").reduce((sum,p)=>sum+p.amount,0);const projected=available-pending;
  const selectedMonthStart = monthStart(selectedMonth);
  const page=view==="Resumen"?<DashboardView month={selectedMonthStart} refreshKey={transactions.length+payments.length} setView={setView}/>:view==="Movimientos"?<TransactionsView month={selectedMonthStart} refreshKey={transactions.length}/>:view==="Presupuesto"?<BudgetView month={selectedMonth} onMonthChange={setSelectedMonth}/>:view==="Cuentas"?<AccountsView pending={payments}/>:<PaymentsView month={selectedMonthStart} refreshKey={payments.length}/>;
  return <AuthGate><div className="shell"><Sidebar view={view} setView={setView}/><main className="main"><header className="topbar"><div><p className="eyebrow">FINANZAS FAMILIARES</p><h1>{view}</h1></div><div className="top-actions"><label className="period month-filter"><CalendarDays size={17}/><span>{monthLabel(selectedMonth)}</span><ChevronDown size={16}/><input aria-label="Filtrar por mes" type="month" value={selectedMonth} onChange={event=>setSelectedMonth(event.target.value)}/></label><button className="primary" onClick={()=>setModal("transaction")}><Plus size={18}/> Nuevo movimiento</button></div></header>{page}</main>{modal&&<EntryModal type={modal} onClose={()=>setModal(null)} onTransaction={item=>setTransactions(x=>[item,...x])} onPayment={item=>setPayments(x=>[item,...x])}/>}<AssistantWidget/></div></AuthGate>;
}

function Sidebar({view,setView}:{view:View;setView:(v:View)=>void}){const links:[View,React.ReactNode][]=[["Resumen",<LayoutDashboard key="1"/>],["Movimientos",<ReceiptText key="2"/>],["Presupuesto",<Target key="3"/>],["Cuentas",<WalletCards key="4"/>],["Pagos",<CircleDollarSign key="5"/>]];return <aside className="sidebar"><div className="brand"><span>c</span><strong>clara</strong></div><nav>{links.map(([label,icon])=><button className={view===label?"active":""} onClick={()=>setView(label)} key={label}>{icon}{label}</button>)}</nav><div className="side-bottom"><div className="demo"><span>Supabase activo</span><small>Los datos se guardan de forma segura en la nube.</small></div><button><Settings/>Configuración</button><div className="profile"><span>GC</span><div><strong>Guada Cruz</strong><small>Cuenta familiar</small></div></div></div></aside>}
function Stat({label,value,note,icon,warn,featured}:{label:string;value:number;note:string;icon:React.ReactNode;warn?:boolean;featured?:boolean}){return <div className={`stat ${featured?"featured":""}`}><div className={warn?"stat-icon warn":"stat-icon"}>{icon}</div><p>{label}</p><strong>{money.format(value)}</strong><small>{note}</small></div>}
function CardTitle({title,action,onClick}:{title:string;action:string;onClick:()=>void}){return <div className="card-title"><h3>{title}</h3><button onClick={onClick}>{action} →</button></div>}
function TransactionTable({items}:{items:Transaction[]}){return <div className="table"><div className="tr head"><span>FECHA</span><span>DETALLE</span><span>CATEGORÍA</span><span>CUENTA</span><span>IMPORTE</span></div>{items.map(t=><div className="tr" key={t.id}><span>{shortDate(t.date)}</span><strong>{t.description}</strong><span><i className="mini-dot"/>{t.category}</span><span>{t.account}</span><strong className="negative">− {money.format(t.amount)}</strong></div>)}</div>}
function Transactions({items}:{items:Transaction[]}){return <div className="content"><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Buscar movimientos…"/></div><button className="period">Todos los tipos <ChevronDown size={16}/></button></div><section className="card"><CardTitle title="Movimientos del mes" action={`${items.length} registros`} onClick={()=>{}}/><TransactionTable items={items}/></section></div>}
function Budget(){const total=budgets.reduce((s,b)=>s+b.planned,0);const actual=budgets.reduce((s,b)=>s+b.actual,0);return <div className="content"><section className="stat-grid"><Stat label="Presupuesto mensual" value={total} note="Plan total de julio" icon={<Target/>}/><Stat label="Gasto real" value={actual} note={`${Math.round(actual/total*100)}% utilizado`} icon={<ReceiptText/>}/><Stat label="Restante" value={total-actual} note="Disponible para el mes" featured icon={<WalletCards/>}/></section><section className="card"><CardTitle title="Plan vs. real por categoría" action="Julio 2026" onClick={()=>{}}/><div className="category-grid">{budgets.map((b,i)=><div className="category-row" key={b.category}><span className={`cat c${i}`}/><div><strong>{b.category}</strong><small>{money.format(b.actual)} gastado</small></div><div className="bar"><i style={{width:`${Math.min(100,b.actual/b.planned*100)}%`}}/></div><strong>{money.format(b.planned-b.actual)}</strong></div>)}</div></section></div>}
function Payments({items,onToggle}:{items:Payment[];onToggle:(id:string)=>void}){return <div className="content"><section className="card"><CardTitle title="Órdenes de pago" action={`${items.filter(x=>x.status==="pending").length} pendientes`} onClick={()=>{}}/><div className="payment-table">{items.map(p=><div key={p.id}><button onClick={()=>onToggle(p.id)} className={p.status==="paid"?"check checked":"check"}>{p.status==="paid"?"✓":""}</button><time>{shortDate(p.due)}</time><p>{p.description}<small>{p.category} · {p.account}</small></p><strong>{money.format(p.amount)}</strong><span className={`pill ${p.status}`}>{p.status==="paid"?"Pagado":"Pendiente"}</span></div>)}</div></section></div>}
function Dashboard({available,pending,projected,transactions,payments,setView}:{available:number;pending:number;projected:number;transactions:Transaction[];payments:Payment[];setView:(v:View)=>void}){return <div className="content"><section className="welcome"><div><h2>Tu dinero, más claro.</h2><p>Una vista simple de cómo viene el mes y qué pagos se acercan.</p></div><div className="health"><span className="dot"/> Mes bajo control</div></section><section className="stat-grid"><Stat label="Disponible total" value={available} note="Efectivo + bancos" icon={<ArrowUpRight/>}/><Stat label="Pagos pendientes" value={pending} note={`${payments.filter(p=>p.status==="pending").length} compromisos`} warn icon={<ArrowDownRight/>}/><Stat label="Disponible proyectado" value={projected} note="Después de pagos pendientes" featured icon={<WalletCards/>}/></section><section className="two-col"><div className="card"><CardTitle title="Presupuesto del mes" action="Ver detalle" onClick={()=>setView("Presupuesto")}/><div className="budget-total"><div><small>Gastado</small><strong>{money.format(budgets.reduce((s,b)=>s+b.actual,0))}</strong></div><div className="right"><small>de {money.format(budgets.reduce((s,b)=>s+b.planned,0))}</small><strong>38%</strong></div></div><div className="bar"><i style={{width:"38%"}}/></div><div className="budget-list">{budgets.slice(0,4).map((b,i)=><div key={b.category}><span className={`cat c${i}`}/><p>{b.category}<small>{money.format(b.actual)} de {money.format(b.planned)}</small></p><strong>{Math.round(b.actual/b.planned*100)}%</strong></div>)}</div></div><div className="card"><CardTitle title="Próximos pagos" action="Ver todos" onClick={()=>setView("Pagos")}/><div className="payment-list">{payments.filter(p=>p.status==="pending").map(p=><div key={p.id}><time>{shortDate(p.due)}</time><p>{p.description}<small>{p.account}</small></p><strong>{money.format(p.amount)}</strong></div>)}</div><button className="soft" onClick={()=>setView("Pagos")}><Plus size={17}/> Agregar pago</button></div></section><section className="card recent"><CardTitle title="Últimos movimientos" action="Ver todos" onClick={()=>setView("Movimientos")}/><TransactionTable items={transactions.slice(0,5)}/></section></div>}
