"use client";

import { FormEvent, useEffect, useState } from "react";
import { LoaderCircle, X } from "lucide-react";
import { useHousehold } from "@/app/family-context";
import type { Payment, Transaction } from "@/lib/types";
import type { DbAccount, DbCategory } from "@/features/accounts/types";
import { createPayment, createTransaction, loadEntryOptions } from "@/features/transactions/service";

export function EntryModal({type,onClose,onTransaction,onPayment}:{type:"transaction"|"payment";onClose:()=>void;onTransaction:(x:Transaction)=>void;onPayment:(x:Payment)=>void}) {
  const household=useHousehold();const isPayment=type==="payment";const [accounts,setAccounts]=useState<DbAccount[]>([]);const [categories,setCategories]=useState<DbCategory[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(!household){setLoading(false);return}loadEntryOptions(household.id).then(data=>{setAccounts(data.accounts);setCategories(data.categories)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[household]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!household)return;const f=new FormData(event.currentTarget);const accountId=String(f.get("account"));const categoryId=String(f.get("category"));const date=String(f.get("date"));const description=String(f.get("description")).trim();const amount=Number(f.get("amount"));const account=accounts.find(a=>a.id===accountId);const category=categories.find(c=>c.id===categoryId);if(!account||!category){setError("Elegí una cuenta y una categoría válidas.");return}setBusy(true);setError("");try{if(isPayment){const id=await createPayment({householdId:household.id,accountId,categoryId,date,description,amount});onPayment({id,due:date,description,category:category.name,account:account.name,amount,status:"pending"})}else{const id=await createTransaction({householdId:household.id,accountId,categoryId,date,description,amount,kind:category.kind});onTransaction({id,date,description,category:category.name,account:account.name,amount})}onClose()}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar el registro.")}finally{setBusy(false)}}
  const usableCategories=categories.filter(c=>isPayment?c.kind==="expense":true);const ready=accounts.length>0&&usableCategories.length>0;
  return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">NUEVO REGISTRO</p><h2>{isPayment?"Agregar pago":"Agregar movimiento"}</h2></div><button type="button" onClick={onClose}><X/></button></div><label>Fecha<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Detalle<input name="description" required placeholder="Ej. Supermercado"/></label><div className="form-row"><label>Categoría<select name="category" required disabled={loading}>{usableCategories.map(c=><option value={c.id} key={c.id}>{c.name} · {c.kind==="income"?"Ingreso":"Gasto"}</option>)}</select></label><label>Cuenta<select name="account" required disabled={loading}>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></div>{!loading&&!ready&&<p className="form-message error">Necesitás crear al menos una cuenta y una categoría.</p>}<label>Importe<input name="amount" type="number" min="0.01" step="0.01" required placeholder="$ 0,00"/></label>{error&&<p className="form-message error">{error}</p>}<button className="primary submit" disabled={loading||busy||!ready}>{loading||busy?<LoaderCircle className="spin"/>:`Guardar ${isPayment?"pago":"movimiento"}`}</button></form></div>
}
