"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ChevronDown, LoaderCircle, Pencil, Search, Trash2, X } from "lucide-react";
import { useHousehold } from "@/app/family-context";
import type { DbAccount, DbCategory } from "@/features/accounts/types";
import { deleteTransaction, listTransactions, loadEntryOptions, updateTransaction, type DbTransaction } from "@/features/transactions/service";

const money=new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0});
const shortDate=(value:string)=>new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short"}).format(new Date(`${value}T12:00:00`));

export function TransactionsView({refreshKey}:{refreshKey:number}){
  const household=useHousehold();const [items,setItems]=useState<DbTransaction[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [query,setQuery]=useState("");const [kind,setKind]=useState<"all"|"income"|"expense">("all");const [editing,setEditing]=useState<DbTransaction|null>(null);
  useEffect(()=>{if(!household)return;setLoading(true);listTransactions(household.id).then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[household,refreshKey]);
  const filtered=useMemo(()=>items.filter(item=>(kind==="all"||item.kind===kind)&&`${item.description} ${item.category_name} ${item.account_name}`.toLowerCase().includes(query.toLowerCase())),[items,kind,query]);
  async function remove(item:DbTransaction){if(!confirm(`¿Eliminar el movimiento “${item.description}”?`))return;try{await deleteTransaction(item.id);setItems(x=>x.filter(t=>t.id!==item.id))}catch(e){setError(e instanceof Error?e.message:"No se pudo eliminar.")}}
  if(loading)return <div className="content empty-state"><LoaderCircle className="spin"/><p>Cargando movimientos…</p></div>;
  return <div className="content"><div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar movimientos…"/></div><label className="filter-select"><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="all">Todos los tipos</option><option value="expense">Gastos</option><option value="income">Ingresos</option></select><ChevronDown size={16}/></label></div>{error&&<p className="form-message error">{error}</p>}<section className="card"><div className="card-title"><h3>Movimientos</h3><span>{filtered.length} registros</span></div>{filtered.length===0?<div className="category-empty">No hay movimientos para este filtro.</div>:<div className="table transaction-real"><div className="tr head"><span>FECHA</span><span>DETALLE</span><span>CATEGORÍA</span><span>CUENTA</span><span>IMPORTE</span><span/></div>{filtered.map(item=><div className="tr" key={item.id}><span>{shortDate(item.transaction_date)}</span><strong>{item.description}</strong><span>{item.category_name}</span><span>{item.account_name}</span><strong className={item.kind==="expense"?"negative":"positive"}>{item.kind==="expense"?"− ":"+ "}{money.format(item.amount)}</strong><span className="row-actions"><button aria-label={`Editar ${item.description}`} onClick={()=>setEditing(item)}><Pencil/></button><button aria-label={`Eliminar ${item.description}`} onClick={()=>remove(item)}><Trash2/></button></span></div>)}</div>}</section>{editing&&household&&<EditTransactionModal item={editing} householdId={household.id} onClose={()=>setEditing(null)} onSaved={saved=>{setItems(x=>x.map(t=>t.id===saved.id?saved:t));setEditing(null)}}/>}</div>
}

function EditTransactionModal({item,householdId,onClose,onSaved}:{item:DbTransaction;householdId:string;onClose:()=>void;onSaved:(x:DbTransaction)=>void}){
  const [accounts,setAccounts]=useState<DbAccount[]>([]);const [categories,setCategories]=useState<DbCategory[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{loadEntryOptions(householdId).then(data=>{setAccounts(data.accounts);setCategories(data.categories)}).catch(e=>setError(e.message))},[householdId]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const accountId=String(f.get("account"));const categoryId=String(f.get("category"));const category=categories.find(c=>c.id===categoryId);const account=accounts.find(a=>a.id===accountId);if(!category||!account)return;const values={accountId,categoryId,date:String(f.get("date")),description:String(f.get("description")).trim(),amount:Number(f.get("amount")),kind:category.kind};setBusy(true);try{await updateTransaction(item.id,values);onSaved({...item,transaction_date:values.date,description:values.description,amount:values.amount,kind:values.kind,account_id:accountId,category_id:categoryId,account_name:account.name,category_name:category.name})}catch(err){setError(err instanceof Error?err.message:"No se pudo guardar.")}finally{setBusy(false)}}
  return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">MOVIMIENTO</p><h2>Editar movimiento</h2></div><button type="button" onClick={onClose}><X/></button></div><label>Fecha<input name="date" type="date" required defaultValue={item.transaction_date}/></label><label>Detalle<input name="description" required defaultValue={item.description}/></label><div className="form-row"><label>Categoría<select name="category" defaultValue={item.category_id}>{categories.map(c=><option value={c.id} key={c.id}>{c.name} · {c.kind==="income"?"Ingreso":"Gasto"}</option>)}</select></label><label>Cuenta<select name="account" defaultValue={item.account_id}>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></div><label>Importe<input name="amount" type="number" min="0.01" step="0.01" required defaultValue={item.amount}/></label>{error&&<p className="form-message error">{error}</p>}<button className="primary submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:"Guardar cambios"}</button></form></div>
}
