"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowRightLeft, LoaderCircle, Pencil, Plus, Trash2, WalletCards, X } from "lucide-react";
import type { Payment } from "@/lib/types";
import { useHousehold } from "@/app/family-context";
import { deleteAccount, deleteCategory, listAccountMovements, listAccounts, listCategories, saveAccount, saveCategory } from "@/features/accounts/service";
import type { DbAccount, DbCategory } from "@/features/accounts/types";
import { calculateAccountBalance, type FinancialMovement } from "@/lib/finance";
import { createTransfer } from "@/features/transfers/service";

const money=new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0});
const accountKinds={cash:"EFECTIVO",bank:"CUENTA BANCARIA",wallet:"BILLETERA VIRTUAL"};

export function AccountsView({pending}:{pending:Payment[]}){
  const household=useHousehold();const [items,setItems]=useState<DbAccount[]>([]);const [movements,setMovements]=useState<FinancialMovement[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [editing,setEditing]=useState<DbAccount|null|undefined>(undefined);const [transferOpen,setTransferOpen]=useState(false);
  async function reload(){if(!household)return;const [accountData,movementData]=await Promise.all([listAccounts(household.id),listAccountMovements(household.id)]);setItems(accountData);setMovements(movementData)}
  useEffect(()=>{reload().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[household]);
  async function remove(item:DbAccount){if(!confirm(`¿Eliminar la cuenta ${item.name}?`))return;try{await deleteAccount(item.id);setItems(x=>x.filter(a=>a.id!==item.id))}catch(e){setError(e instanceof Error?e.message:"No se pudo eliminar la cuenta.")}}
  if(loading)return <div className="content empty-state"><LoaderCircle className="spin"/><p>Cargando cuentas…</p></div>;
  return <div className="content"><div className="section-heading"><div><h2>Tus cuentas</h2><p>Efectivo, bancos y billeteras de la familia.</p></div><div className="heading-actions"><button className="soft compact" disabled={items.length<2} onClick={()=>setTransferOpen(true)}><ArrowRightLeft size={17}/> Transferir</button><button className="primary" onClick={()=>setEditing(null)}><Plus size={17}/> Nueva cuenta</button></div></div>{error&&<p className="form-message error">{error}</p>}{items.length===0?<div className="card empty-state"><WalletCards/><h3>Todavía no hay cuentas</h3><p>Creá la primera para empezar a registrar saldos y movimientos.</p><button className="primary" onClick={()=>setEditing(null)}><Plus size={17}/> Crear cuenta</button></div>:<div className="account-grid">{items.map(a=>{const balance=calculateAccountBalance({id:a.id,openingBalance:Number(a.opening_balance)},movements);const commitments=pending.filter(p=>p.account===a.name&&p.status==="pending").reduce((s,p)=>s+p.amount,0);return <article className="account" key={a.id} style={{"--accent":a.color} as React.CSSProperties}><div className="account-head"><span>{a.name.slice(0,2).toUpperCase()}</span><small>{accountKinds[a.kind]}</small></div><div className="account-actions"><button aria-label="Editar" onClick={()=>setEditing(a)}><Pencil/></button><button aria-label="Eliminar" onClick={()=>remove(a)}><Trash2/></button></div><p>Saldo actual</p><strong>{money.format(balance)}</strong><div><small>Comprometido</small><b>{money.format(commitments)}</b></div><div><small>Proyectado</small><b>{money.format(balance-commitments)}</b></div></article>})}</div>}<CategoriesManager/>{editing!==undefined&&household&&<AccountModal account={editing} householdId={household.id} onClose={()=>setEditing(undefined)} onSaved={saved=>{setItems(x=>editing?x.map(a=>a.id===saved.id?saved:a):[...x,saved]);setEditing(undefined)}}/>}{transferOpen&&<TransferModal accounts={items} onClose={()=>setTransferOpen(false)} onSaved={()=>{setTransferOpen(false);reload().catch(e=>setError(e.message))}}/>}</div>
}

function TransferModal({accounts,onClose,onSaved}:{accounts:DbAccount[];onClose:()=>void;onSaved:()=>void}){const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const sourceAccount=String(f.get("source"));const destinationAccount=String(f.get("destination"));if(sourceAccount===destinationAccount){setError("La cuenta de origen y destino deben ser diferentes.");return}setBusy(true);setError("");try{await createTransfer({sourceAccount,destinationAccount,date:String(f.get("date")),description:String(f.get("description")).trim(),amount:Number(f.get("amount"))});onSaved()}catch(err){setError(err instanceof Error?err.message:"No se pudo realizar la transferencia.")}finally{setBusy(false)}}return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">ENTRE CUENTAS</p><h2>Nueva transferencia</h2></div><button type="button" onClick={onClose}><X/></button></div><div className="form-row"><label>Desde<select name="source" required>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Hacia<select name="destination" required defaultValue={accounts[1]?.id}>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></div><label>Fecha<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Detalle<input name="description" maxLength={100} defaultValue="Transferencia entre cuentas"/></label><label>Importe<input name="amount" type="number" min="0.01" step="0.01" required placeholder="$ 0,00"/></label>{error&&<p className="form-message error">{error}</p>}<button className="primary submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<><ArrowRightLeft size={17}/> Transferir</>}</button></form></div>}

function AccountModal({account,householdId,onClose,onSaved}:{account:DbAccount|null;householdId:string;onClose:()=>void;onSaved:(a:DbAccount)=>void}){const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{onSaved(await saveAccount({household_id:householdId,name:String(f.get("name")).trim(),kind:String(f.get("kind")) as DbAccount["kind"],opening_balance:Number(f.get("balance")),color:String(f.get("color"))},account?.id))}catch(err){setError(err instanceof Error?err.message:"No se pudo guardar.")}finally{setBusy(false)}}return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">CUENTAS</p><h2>{account?"Editar cuenta":"Nueva cuenta"}</h2></div><button type="button" onClick={onClose}><X/></button></div><label>Nombre<input name="name" required maxLength={60} defaultValue={account?.name}/></label><div className="form-row"><label>Tipo<select name="kind" defaultValue={account?.kind||"bank"}><option value="cash">Efectivo</option><option value="bank">Cuenta bancaria</option><option value="wallet">Billetera virtual</option></select></label><label>Color<input name="color" type="color" defaultValue={account?.color||"#20e88f"}/></label></div><label>Saldo inicial<input name="balance" type="number" step="0.01" required defaultValue={account?.opening_balance||0}/></label>{error&&<p className="form-message error">{error}</p>}<button className="primary submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:account?"Guardar cambios":"Crear cuenta"}</button></form></div>}

function CategoriesManager(){const household=useHousehold();const [items,setItems]=useState<DbCategory[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [editing,setEditing]=useState<DbCategory|null|undefined>(undefined);useEffect(()=>{if(!household){setLoading(false);return}listCategories(household.id).then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[household]);async function remove(item:DbCategory){if(!confirm(`¿Eliminar la categoría ${item.name}?`))return;try{await deleteCategory(item.id);setItems(x=>x.filter(c=>c.id!==item.id))}catch{setError("No se puede eliminar porque está siendo utilizada.")}}return <section className="categories-section"><div className="section-heading"><div><h2>Categorías</h2><p>Organizá ingresos y gastos para entender mejor el presupuesto.</p></div><button className="primary" onClick={()=>setEditing(null)}><Plus size={17}/> Nueva categoría</button></div>{error&&<p className="form-message error">{error}</p>}{loading?<div className="card category-empty"><LoaderCircle className="spin"/> Cargando categorías…</div>:items.length===0?<div className="card category-empty">Todavía no hay categorías. Creá la primera para clasificar movimientos.</div>:<div className="category-columns">{(["expense","income"] as const).map(kind=><div className="card" key={kind}><div className="category-column-title"><h3>{kind==="expense"?"Gastos":"Ingresos"}</h3><span>{items.filter(x=>x.kind===kind).length}</span></div><div className="category-items">{items.filter(x=>x.kind===kind).map(item=><div key={item.id}><span className={`category-kind ${kind}`}/><strong>{item.name}</strong><button aria-label={`Editar ${item.name}`} onClick={()=>setEditing(item)}><Pencil/></button><button aria-label={`Eliminar ${item.name}`} onClick={()=>remove(item)}><Trash2/></button></div>)}</div></div>)}</div>}{editing!==undefined&&household&&<CategoryModal category={editing} householdId={household.id} onClose={()=>setEditing(undefined)} onSaved={saved=>{setItems(x=>editing?x.map(c=>c.id===saved.id?saved:c):[...x,saved]);setEditing(undefined)}}/>}</section>}

function CategoryModal({category,householdId,onClose,onSaved}:{category:DbCategory|null;householdId:string;onClose:()=>void;onSaved:(c:DbCategory)=>void}){const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{onSaved(await saveCategory({household_id:householdId,name:String(f.get("name")).trim(),kind:String(f.get("kind")) as DbCategory["kind"]},category?.id))}catch(err){const value=err as {code?:string;message?:string};setError(value.code==="23505"?"Ya existe una categoría con ese nombre.":value.message||"No se pudo guardar.")}finally{setBusy(false)}}return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">CATEGORÍAS</p><h2>{category?"Editar categoría":"Nueva categoría"}</h2></div><button type="button" onClick={onClose}><X/></button></div><label>Nombre<input name="name" required maxLength={60} defaultValue={category?.name}/></label><label>Tipo<select name="kind" defaultValue={category?.kind||"expense"}><option value="expense">Gasto</option><option value="income">Ingreso</option></select></label>{error&&<p className="form-message error">{error}</p>}<button className="primary submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:category?"Guardar cambios":"Crear categoría"}</button></form></div>}
